// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appstate.sql

package sqlitedb

import (
	"context"
)

const createAppState = `-- name: CreateAppState :one
INSERT INTO app_state (
    selected_project_id
) VALUES (
    ?
)
RETURNING id, selected_project_id, created_at, updated_at
`

func (q *Queries) CreateAppState(ctx context.Context, selectedProjectID *int64) (*AppState, error) {
	row := q.db.QueryRowContext(ctx, createAppState, selectedProjectID)
	var i AppState
	err := row.Scan(
		&i.ID,
		&i.SelectedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAppState = `-- name: GetAppState :one
SELECT id, selected_project_id, created_at, updated_at FROM app_state
LIMIT 1
`

func (q *Queries) GetAppState(ctx context.Context) (*AppState, error) {
	row := q.db.QueryRowContext(ctx, getAppState)
	var i AppState
	err := row.Scan(
		&i.ID,
		&i.SelectedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAppState = `-- name: UpdateAppState :one
UPDATE app_state
SET
    selected_project_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, selected_project_id, created_at, updated_at
`

func (q *Queries) UpdateAppState(ctx context.Context, selectedProjectID *int64) (*AppState, error) {
	row := q.db.QueryRowContext(ctx, updateAppState, selectedProjectID)
	var i AppState
	err := row.Scan(
		&i.ID,
		&i.SelectedProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
