// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package sqlitedb

import (
	"context"
)

const createList = `-- name: CreateList :one
INSERT INTO list (
    title, 
    parent_list_id
) VALUES (
    ?, ?
) RETURNING id, title, parent_list_id, created_at, updated_at
`

type CreateListParams struct {
	Title        string
	ParentListID *int64
}

func (q *Queries) CreateList(ctx context.Context, arg *CreateListParams) (*List, error) {
	row := q.db.QueryRowContext(ctx, createList, arg.Title, arg.ParentListID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentListID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM list
WHERE id = ?
`

func (q *Queries) DeleteList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteList, id)
	return err
}

const getList = `-- name: GetList :one
SELECT id, title, parent_list_id, created_at, updated_at FROM list
WHERE id = ? LIMIT 1
`

func (q *Queries) GetList(ctx context.Context, id int64) (*List, error) {
	row := q.db.QueryRowContext(ctx, getList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentListID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllLists = `-- name: ListAllLists :many
SELECT id, title, parent_list_id, created_at, updated_at FROM list
`

func (q *Queries) ListAllLists(ctx context.Context) ([]*List, error) {
	rows, err := q.db.QueryContext(ctx, listAllLists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentListID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListsByParentListID = `-- name: ListListsByParentListID :many
SELECT id, title, parent_list_id, created_at, updated_at FROM list
WHERE parent_list_id = ?
`

func (q *Queries) ListListsByParentListID(ctx context.Context, parentListID *int64) ([]*List, error) {
	rows, err := q.db.QueryContext(ctx, listListsByParentListID, parentListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*List{}
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentListID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateList = `-- name: UpdateList :one
UPDATE list
SET
    title = ?,
    parent_list_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, parent_list_id, created_at, updated_at
`

type UpdateListParams struct {
	Title        string
	ParentListID *int64
	ID           int64
}

func (q *Queries) UpdateList(ctx context.Context, arg *UpdateListParams) (*List, error) {
	row := q.db.QueryRowContext(ctx, updateList, arg.Title, arg.ParentListID, arg.ID)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentListID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
