// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type Task struct {
	ID        int64
	Title     string
	Complete  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
