// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type AppState struct {
	ID                int64
	SelectedProjectID *int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Project struct {
	ID              int64
	Title           string
	ParentProjectID *int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Task struct {
	ID           int64
	Title        string
	ParentTaskID *int64
	ProjectID    *int64
	Complete     bool
	DueAt        *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
