// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitedb

import (
	"time"
)

type List struct {
	ID           int64
	Title        string
	ParentListID *int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Task struct {
	ID           int64
	Title        string
	ParentTaskID *int64
	ListID       *int64
	Complete     bool
	DueAt        *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
