// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project.sql

package sqlitedb

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (
    title,
    parent_project_id
) VALUES (
    ?, ?
) RETURNING id, title, parent_project_id, created_at, updated_at
`

type CreateProjectParams struct {
	Title           string
	ParentProjectID *int64
}

func (q *Queries) CreateProject(ctx context.Context, arg *CreateProjectParams) (*Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Title, arg.ParentProjectID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM project
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, title, parent_project_id, created_at, updated_at FROM project
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (*Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT id, title, parent_project_id, created_at, updated_at FROM project
`

func (q *Queries) ListAllProjects(ctx context.Context) ([]*Project, error) {
	rows, err := q.db.QueryContext(ctx, listAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByParentProjectID = `-- name: ListProjectsByParentProjectID :many
SELECT id, title, parent_project_id, created_at, updated_at FROM project
WHERE parent_project_id = ?
`

func (q *Queries) ListProjectsByParentProjectID(ctx context.Context, parentProjectID *int64) ([]*Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByParentProjectID, parentProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE project
SET
    title = ?,
    parent_project_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, parent_project_id, created_at, updated_at
`

type UpdateProjectParams struct {
	Title           string
	ParentProjectID *int64
	ID              int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg *UpdateProjectParams) (*Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Title, arg.ParentProjectID, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
