// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlitedb

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (
    title, details, complete
) VALUES (
    ?, ?, ?
) RETURNING id, title, details, complete, created_at, updated_at
`

type CreateTaskParams struct {
	Title    string
	Details  *string
	Complete bool
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (*Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.Title, arg.Details, arg.Complete)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.Complete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, details, complete, created_at, updated_at FROM task
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (*Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.Complete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, title, details, complete, created_at, updated_at FROM task
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Details,
			&i.Complete,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE task
SET
    title = ?,
    details = ?,
    complete = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, details, complete, created_at, updated_at
`

type UpdateTaskParams struct {
	Title    string
	Details  *string
	Complete bool
	ID       int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg *UpdateTaskParams) (*Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Details,
		arg.Complete,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Details,
		&i.Complete,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
