// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlitedb

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (
    title, 
    parent_task_id, 
    list_id, 
    complete,
    due_at
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title        string
	ParentTaskID *int64
	ListID       *int64
	Complete     bool
	DueAt        *time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (*Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.ParentTaskID,
		arg.ListID,
		arg.Complete,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentTaskID,
		&i.ListID,
		&i.Complete,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM task
WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at FROM task
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (*Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentTaskID,
		&i.ListID,
		&i.Complete,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllTasks = `-- name: ListAllTasks :many
SELECT id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at FROM task
`

func (q *Queries) ListAllTasks(ctx context.Context) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentTaskID,
			&i.ListID,
			&i.Complete,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByListID = `-- name: ListTasksByListID :many
SELECT id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at FROM task
WHERE list_id = ?
`

func (q *Queries) ListTasksByListID(ctx context.Context, listID *int64) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByListID, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentTaskID,
			&i.ListID,
			&i.Complete,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByParentTaskID = `-- name: ListTasksByParentTaskID :many
SELECT id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at FROM task
WHERE parent_task_id = ?
`

func (q *Queries) ListTasksByParentTaskID(ctx context.Context, parentTaskID *int64) ([]*Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByParentTaskID, parentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ParentTaskID,
			&i.ListID,
			&i.Complete,
			&i.DueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE task
SET
    title = ?,
    parent_task_id = ?,
    list_id = ?,
    complete = ?,
    due_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, parent_task_id, list_id, complete, due_at, created_at, updated_at
`

type UpdateTaskParams struct {
	Title        string
	ParentTaskID *int64
	ListID       *int64
	Complete     bool
	DueAt        *time.Time
	ID           int64
}

func (q *Queries) UpdateTask(ctx context.Context, arg *UpdateTaskParams) (*Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.ParentTaskID,
		arg.ListID,
		arg.Complete,
		arg.DueAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ParentTaskID,
		&i.ListID,
		&i.Complete,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
