CREATE TABLE IF NOT EXISTS list (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL, 
    parent_list_id INTEGER REFERENCES list(id) ON DELETE CASCADE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS task (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    parent_task_id INTEGER REFERENCES task(id) ON DELETE CASCADE,
    list_id INTEGER REFERENCES list(id) ON DELETE CASCADE,
    complete BOOLEAN NOT NULL DEFAULT false,
    due_at DATETIME,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
