CREATE TABLE IF NOT EXISTS task (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    complete BOOLEAN NOT NULL DEFAULT false,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
